# Site Settings
name: "Mageplaza"
title: "Mageplaza"
slogan: "Magento® extension store"
description: "Better Magento Extension Store"
email: "support@mageplaza.com"
url: "http://staging.mageplaza.com"
baseurl: "http://staging.mageplaza.com"
domain: "staging.mageplaza.com"
author: "mageplaza"
this_year: "2016"
phone: "+12122459600"

allow_search_engine: false


paypal: "support@mageplaza.com"

google_verify: "mqeRPCxfPDdd8Ai589_r1ylvomMFyjYC0epneqbK74"
bing_verify: 
google_analytics: "UA-74427984-10"

# Social accounts
google_plus: 
disqus_shortname: "mageplaza"

subcriber_url: "http://t.us3.list-manage1.com/subscribe/post?u=531af730d34352cf489&amp;id=0416bef2d9"

# Build Settings
markdown: kramdown
encoding: UTF-8

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# http://jekyllrb.com/docs/permalinks/
# /:title/ /:title.html
permalink:   "/:categories/:title/"

# Amount of post to show on home page
paginate: 5
paginate_path: "/blog/page:num/"

future:      true
highlighter: rouge

gems:
  - jekyll-redirect-from
  # http://jekyllrb.com/docs/templates/#gist
  # - jekyll-gist
  # - jekyll-less



include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor"]


collections:
  pages:
    output: true


